// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izryvglbxnnvyajohtsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cnl2Z2xieG5udnlham9odHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjUyNjksImV4cCI6MjA2MzE0MTI2OX0.zJU9D1khMeLvNn_PnVcvQ1Jo6mq78i5WzcuSDzWxJoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);